definitions:
  dtos.RegisterUserRequestDto:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      userName:
        type: string
    type: object
  dtos.RegisterUserResponseDto:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      userId:
        type: string
      userName:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/users:
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: User data
        in: body
        name: RegisterUserRequestDto
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterUserRequestDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RegisterUserResponseDto'
      security:
      - ApiKeyAuth: []
      summary: Register user
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
