version: "3.3"
services:

    #######################################################
    #  Rabbitmq
    #######################################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - shop


    #######################################################
    #  Mongo
    #######################################################
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - shop
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db


    #######################################################
    #  Postgress
    #######################################################
  postgres:
   container_name: postgres
   image: postgres:13-alpine
   restart: unless-stopped
   ports:
    - '5432:5432'
   environment:
    - POSTGRES_USER=postgress
    - POSTGRES_PASSWORD=postgress
   networks:
    - shop


    #######################################################
    #  Jaeger
    #######################################################
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - shop
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686    
      
  
networks:
  shop:
    name: shop


volumes:
  mongo:
    driver: local



