# https://github.com/amannn/action-semantic-pull-request
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

name: Conventional Commits Checks

on:
  workflow_run:
    workflows: ["Release Drafter Auto Labeler"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  check-conventional-commits-labels:
    name: Check conventional commits labels
    runs-on: [ self-hosted ]
    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: feature,fix,changed,deprecated,removed,security,docs,dependencies
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  validate-pull-request-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
