# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" , "develop"]
    paths-ignore:
     - "README.md"
     - "CHANGELOG.md"
  pull_request:
    branches: [ "main" , "develop" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: pkg build
      working-directory: ./internal/pkg
      run: go build -v ./...
      
    - name: identity-service build
      working-directory: ./internal/services/identity-service
      run: go test -v ./...

    - name: identity-service tests
      working-directory: ./internal/services/identity-service
      run: go build -v ./...

    - name: product-service build
      working-directory: ./internal/services/product-service
      run: go build -v ./...

    - name: product-service tests
      working-directory: ./internal/services/product-service
      run: go test -v ./...
